### ISSUE TITLE
Possible feature flaw about the call history page

### ISSUE THREAD

**Issue by Zenkoh1** [AY2425S1-CS2103T-F14b-3/tp#107]
@zyng233 not sure if they will count this as a feature flaw for your feature but

you might want to check which screen they are on to allow/disallow certain commands

ie. if they are on the `history 2` screen, you might want to disable the mark by index command?

up for discussion

**Comment by zyng233** [comment]
ok, I will disable the commands that will modify data (e.g. delete, edit, mark) if user is in the history view. So that user has to navigate back to the person list before modifying the data.
