### ISSUE TITLE
Standardise all UG/DG images

### ISSUE THREAD

**Issue by Zenkoh1** [AY2425S1-CS2103T-F14b-3/tp#109]
With respect to the size and cropping

**Comment by zyng233** [comment]
maybe we need to change the screenshots that include the tags like 'family' and 'friends' as these tags don't seem logical in this context

**Comment by Zenkoh1** [comment]
Ye good catch, added another issue for that for now #117

**Comment by GabrielCWT** [comment]
Closed by https://github.com/AY2425S1-CS2103T-F14b-3/tp/pull/187
