### ISSUE TITLE
Change name validation?

### ISSUE THREAD

**Issue by Zenkoh1** [AY2425S1-CS2103T-F14b-3/tp#140]
<img width="512" alt="image" src="https://github.com/user-attachments/assets/61e4c606-3132-4d1c-831f-221b70c11cd5">

Do we need to change the AB3 default behaviour to address this

**Comment by GabrielCWT** [comment]
I feel like this could be a problem but as I think the line "If the input is expected to match the legal name of the person" implies that it is only a problem if it is required to match the NRIC name for example. In our case, we only need the NRIC to be exactly as it is stated, names can be a nickname or anything the employee would like. Therefore, I don't think this is an issue. Feel free to continue this discussion but if you agree then we can close this issue.

**Comment by Zenkoh1** [comment]
> I feel like this could be a problem but as I think the line "If the input is expected to match the legal name of the person" implies that it is only a problem if it is required to match the NRIC name for example. In our case, we only need the NRIC to be exactly as it is stated, names can be a nickname or anything the employee would like. Therefore, I don't think this is an issue. Feel free to continue this discussion but if you agree then we can close this issue.

sure, actually we should probably create like a rebuttal document to note down our rebuttals to common "bugs" people might find
