### ISSUE TITLE
Person or Elderly in dg?

### ISSUE THREAD

**Issue by linette-g** [AY2425S1-CS2103T-F14b-3/tp#158]
Up for discussion. I changed everything to `elderly` in the user guide to adhere to the cs2101 grading but I don't think the dev guide is graded for being user-oriented? (can correct me on this)

**Comment by GabrielCWT** [comment]
I think it would be good to just standardise it to elderly

**Comment by GabrielCWT** [comment]
Closed with https://github.com/AY2425S1-CS2103T-F14b-3/tp/pull/178
