### ISSUE TITLE
When find command is used on two people, elderly is used not elderlies

### ISSUE THREAD

**Issue by brendanng7** [AY2425S1-CS2103T-F14b-3/tp#163]
![image](https://github.com/user-attachments/assets/ab6208af-4fde-42f1-a9a5-eaec96662052)
Im not sure if this is a bug, but bringing this up to check.

**Comment by Zenkoh1** [comment]
I think elderly can be considered plural
<img width="369" alt="image" src="https://github.com/user-attachments/assets/9ad56525-1120-4ac3-a403-071b630c5c8e">
