### ISSUE TITLE
Add clarification on what is personList and historyList in UG

### ISSUE THREAD

**Issue by brendanng7** [AY2425S1-CS2103T-F14b-3/tp#167]

**Comment by Zenkoh1** [comment]
and DG

**Comment by zyng233** [comment]
It is already defined in the glossary in DG. Maybe can add the clarification of personList in ug cos historyList is not used in ug.

**Comment by GabrielCWT** [comment]
Will be adding personList and not historyList. As @zyng233 has mentioned, historyList is not in the UG
