### ISSUE TITLE
Redudant extension in use case?

### ISSUE THREAD

**Issue by Zenkoh1** [AY2425S1-CS2103T-F14b-3/tp#172]
<img width="536" alt="image" src="https://github.com/user-attachments/assets/d65ace6d-a6a4-46f8-85e4-bdf6faa52c89">

Honestly i don't exactly know, but is this extension necessary, given that the first step of the MSS is already to do the `list` command

**Comment by zyng233** [comment]
I think that if user strictlly follow the flow, then they will be in the correct list view. But including the detection of list view can provide more info in case of the steps are not followed correctly like users use history command and end up in historyList view.

**Comment by Zenkoh1** [comment]
I think in the context of a use case, we don't need to account for cases that are not explicitly stated?

Let's say we need to account for all scenarios that might lead to an extension, even if that scenario requires whole other action that isn't in the MSS.
A bit of an extreme example, but what if we also need to think about whether the user deleted the elderly after step 2, then we will also need to write an extension for that.

**Comment by Zenkoh1** [comment]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/56ed4dad-d2f5-4c8c-a775-60abf146090b">

also wait is the bullet point a valid notation for Use Cases

**Comment by zyng233** [comment]
![Screenshot 2024-11-02 181922](https://github.com/user-attachments/assets/62466e12-00f0-478a-b4ee-dc6128701024)
As I guess like we should add the alternate scenarios where something could go wrong? e.g. when the user gives a valid command but it fails to execute. For other extreme examples like delete, if user wants to mark a deleted elderly, this scenario is alr covered by 3a. 
But if u think like this is unnecessary, I can remove them.

For bullet point, I didn't see they explicitly mentioned that it is not allowed or I might hv overlooked? To be safe, I can remove them together...

**Comment by Zenkoh1** [comment]
> As I guess like we should add the alternate scenarios where something could go wrong? e.g. when the user gives a valid command but it fails to execute. For other extreme examples like delete, if user wants to mark a deleted elderly, this scenario is alr covered by 3a. But if u think like this is unnecessary, I can remove them.

I'm okay with anything ah, it was js a thought

**Comment by zyng233** [comment]
> > As I guess like we should add the alternate scenarios where something could go wrong? e.g. when the user gives a valid command but it fails to execute. For other extreme examples like delete, if user wants to mark a deleted elderly, this scenario is alr covered by 3a. But if u think like this is unnecessary, I can remove them.
> 
> I'm okay with anything ah, it was js a thought

It's okay, just like which one do you think it is better because I am kinda not sure also...
