### ISSUE TITLE
Frame-y scrolling for application

### ISSUE THREAD

**Issue by GabrielCWT** [AY2425S1-CS2103T-F14b-3/tp#179]
Could someone confirm if scrolling the personList is very laggy or is it just my computer. The scrolling of other things i.e. command box is smooth.

**Comment by linette-g** [comment]
Seems fine on my end

**Comment by GabrielCWT** [comment]
> Seems fine on my end

Sad times, we will see if anyone else has the issue... If not i'll close this

**Comment by GabrielCWT** [comment]
Seems to be fixed somehow with the recent PRs
