### ISSUE TITLE
Add Planned Enhancements

### ISSUE THREAD

**Issue by Zenkoh1** [AY2425S1-CS2103T-F14b-3/tp#192]
![image](https://github.com/user-attachments/assets/d92d02d7-1c52-463e-9a87-5c7dfca5ae47)

**Comment by Zenkoh1** [comment]
i realised we can't add unmark, cuz it's a new feature

**Comment by linette-g** [comment]
Maybe if we wanna mention the unmark thing can put under the future improvement part in the ug
