### ISSUE TITLE
[PE-D][Tester C] Mark command could be renamed to something more accurate

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-3/tp#211]
![image.png](https://raw.githubusercontent.com/ghos7ie/ped/main/files/c834f566-286a-49fa-b46a-8c90a0383cbc.png)

Just a minor nitpick, off the bat using the application, I was expecting the command to update the history of the elderly to be something like `call`

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ghos7ie/ped#5

**Comment by GabrielCWT** [comment]
You are right, it's just a nit pick
