### ISSUE TITLE
[PE-D][Tester C] Error not thrown for invalid date in mark command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-3/tp#235]
![image.png](https://raw.githubusercontent.com/ghos7ie/ped/main/files/322e3a14-ee4a-42de-b793-28ac56c4e67c.png)

`mark 1 d/2024-02-30`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ghos7ie/ped#11

**Comment by Zenkoh1** [comment]
Fixed
