### ISSUE TITLE
[PE-D][Tester C] Noticeable lag when running list command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-3/tp#242]
<i><video controls><source src="https://raw.githubusercontent.com/ghos7ie/ped/main/files/c1051e5a-8828-4bc4-8896-a1e02abb3691.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/ghos7ie/ped/main/files/c1051e5a-8828-4bc4-8896-a1e02abb3691.mp4</i>

Noticeable 3 second lag when running list command, clip starts when i pressed enter. Im sorry but onscreen keyboard can't be recorded so  i can't show

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ghos7ie/ped#12

**Comment by GabrielCWT** [comment]
We can increase max allowance time in NFR. But tested with 500 and no lag. :(
