### ISSUE TITLE
[PE-D][Tester D] Results box is too small.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-3/tp#255]
![image.png](https://raw.githubusercontent.com/kyouscrap/ped/main/files/fe6b5eb8-c66e-4391-a01e-56826ead8dde.png)

I have to use my cursor to manually scroll the window to see the entire message. This is counter-intuitive to the focus they have placed on the CLI functionality.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: kyouscrap/ped#15

**Comment by brendanng7** [comment]
Same as #233
