### ISSUE TITLE
[PE-D][Tester E] Add command not allowing names with "/" inside

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-3/tp#258]
For certain names which include "S/O", the add command does not allow as seen in the picture below.

![image.png](https://raw.githubusercontent.com/weijianwong/ped/main/files/96ba2840-a2f8-48a1-90e1-37d921358469.png)

Perhaps consider removing this limitation from add, as there are many people with names that include "S/O". 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: weijianwong/ped#15

**Comment by GabrielCWT** [comment]
Duplicate of https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/208
