### ISSUE TITLE
[PE-D][Tester D] User Guide does not have any description for notes.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-3/tp#259]
There is no mention of the description and constraints for the NOTES field anywhere in the user guide.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: kyouscrap/ped#17

**Comment by GabrielCWT** [comment]
We only disallow "o/" For notes. Can someone else confirm this by testing it out before I add it into the docs?

**Comment by Zenkoh1** [comment]
> We only disallow "o/" For notes. Can someone else confirm this by testing it out before I add it into the docs?

This is a more general constraint right (ie. a/ cnfm cannot have a/ in the address)
