### ISSUE TITLE
Add search by nric

### ISSUE THREAD

**Issue by Zenkoh1** [AY2425S1-CS2103T-F14b-3/tp#89]
can implement if we got time

**Comment by brendanng7** [comment]
I was thinking the command could be used in this ways:
find Alex
find Alex S7083906G
find S7083906G
for example. what do yall think?

**Comment by Zenkoh1** [comment]
> I was thinking the command could be used in these ways: find Alex find Alex S7083906G find S7083906G for example. what do yall think?

ya that works
